CREATE TABLE FILM
(
	FID INT PRIMARY KEY,
	FNAME VARCHAR(255),
	FTYPE VARCHAR(255),
	DNAME VARCHAR(255),
	FLENGTH INT,
	IS3D VARCHAR(255) CHECK(IS3D='Y' OR IS3D='N'),
	GRADE INT,
	CHECK (GRADE > 0 AND GRADE < 100)
);

CREATE TABLE ACTOR
(
	ACTID INT PRIMARY KEY,
	ANAME VARCHAR(30),
	SEX VARCHAR(2),
	BYEAR INT
);

CREATE TABLE ACTIN
(
	ACTID INT PRIMARY KEY,
	FID INT,
	ISLEADING VARCHAR(1) CHECK(ISLEADING='Y' OR ISLEADING='N'),
	GRADE INT,
	CHECK (GRADE > 0 AND GRADE < 100),
	FOREIGN KEY(FID) REFERENCES FILM(FID),
	FOREIGN KEY(ACTID) REFERENCES ACTOR(ACTID),
	PRIMARY KEY(ACTID, FID)
);

CREATE TABLE THEATER
(
	TID INT PRIMARY KEY,
	TNAME VARCHAR(20),
	TAREA VARCHAR(20),
	ADDRESS VARCHAR(30)
);

CREATE TABLE SHOWT
(
	FID INT,
	TID INT,
	PRICEC INT,
	SYEAR INT,
	SMONTH INT,
	FOREIGN KEY(TID) REFERENCES THEATER(TID),
	FOREIGN KEY(FID) REFERENCES FILM(FID),
	PRIMARY KEY(FID, TID)
);
